### ISSUE TITLE
Port for WearOS 3

### ISSUE THREAD

**Issue by lovelydumpling** [goaaats/xl-authenticator#12]
I imagine it's rather niche so I can understand if it doesn't happen, but as a smartwatch owner, a port for WearOS 3 would be very appreciated so I don't have to dig out my phone every time I log in.

Wear OS 3 is an android based OS for smartwatches that came out this year, and is designed to be a unified platform for smartwatches going forward. Where before watch manufacturers all had their own OS with their own appstores, nowadays companies are working with Google to use Wear OS on watches moving forward, that way they have a healthy app ecosystem. In making a port to Wear OS 3, you'd be making a port for basically all Android smartwatch users to come.

**Comment by reiichi001** [comment]
It's technically supported via Flutter, so this is possible, but unless Goat has a smartwatch, testing it would be pretty difficult. PRs are welcome though!

**Comment by reiichi001** [comment]
This is also a duplicate of https://github.com/goaaats/xl-authenticator/issues/9

**Comment by lovelydumpling** [comment]
oh I'm blind @.@ Totally missed that. Sorry!
