### ISSUE TITLE
Authenticator Generates Invalid 2FA Code

### ISSUE THREAD

**Issue by iRhuel** [goaaats/xl-authenticator#14]
With the last game patch, the authenticator generates (mostly) invalid codes; Sometimes they're valid, but mostly they're not, and it's a race to obtain a valid one before being locked out of authenticating due to too many failed attempts. Both LAN transmission and and manual entry of codes is rejected by FFXIV's auth service as an invalid password.

**Comment by reiichi001** [comment]
Hello! This usually means your phone's time is off-sync. Once that's resolved, you should see it properly align with what SE expects.

**Comment by iRhuel** [comment]
> Hello! This usually means your phone's time is off-sync. Once that's resolved, you should see it properly align with what SE expects.

This was the solution, Thanks!
