### ISSUE TITLE
Mutliple Launcher IPs

### ISSUE THREAD

**Issue by Ethan-BB** [goaaats/xl-authenticator#8]
Good evening,
would be nice if Authentificator allowed entry of multiple IP addresses/hostnames of PCs, so login on for example PC and Notebook are similarly easy. Could be solved with buttons showing which IP/hostname to authenticate.

Thank You.

**Comment by Sloop0** [comment]
> Yes, the same feature I'm also thinking about right now. I have the situation that I'm playing on my own Laptop at home and at my girlfriend on her laptop.
> 
> An alternative way to @Ethan-BB to keep the automatic authentication would be just entering multiple IP-Addresses or Hostnames by seperation with "," or ";". So, as example you input: `DESKTOP-75V1SBP;DESKTOP-62B9KCF;192.168.178.7` And then simply send the OTP to each adress and host in the input.
> 
> I guess that should be more simple then modifying the UI by adding new buttons and/or textfiels. What do you think? @alphaONE2 @goaaats

I just came here to see if anyone had made this suggestion. It would be extremely helpful, especially now that many people are playing on both PC and Steam Deck.

**Comment by goaaats** [comment]
I accepted that I probably won't have time for this in the coming months, so if anyone wants to have a stab at it, feel free. Shouldn't be very hard to do.

**Comment by goaaats** [comment]
Done with #17
